
package cl.cnsv.wsreporteproyeccion.cliente.proyeccion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiciosProyeccion", targetNamespace = "http://ws.proyeccion.cnsv.cl/", wsdlLocation = "http://dconvm203:8080/WS_ProyeccionVidaIndividual/ServiciosProyeccion?wsdl")
public class ServiciosProyeccion_Service
    extends Service
{

    private final static URL SERVICIOSPROYECCION_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSPROYECCION_EXCEPTION;
    private final static QName SERVICIOSPROYECCION_QNAME = new QName("http://ws.proyeccion.cnsv.cl/", "ServiciosProyeccion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dconvm203:8080/WS_ProyeccionVidaIndividual/ServiciosProyeccion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSPROYECCION_WSDL_LOCATION = url;
        SERVICIOSPROYECCION_EXCEPTION = e;
    }

    public ServiciosProyeccion_Service() {
        super(__getWsdlLocation(), SERVICIOSPROYECCION_QNAME);
    }

    public ServiciosProyeccion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSPROYECCION_QNAME, features);
    }

    public ServiciosProyeccion_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSPROYECCION_QNAME);
    }

    public ServiciosProyeccion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSPROYECCION_QNAME, features);
    }

    public ServiciosProyeccion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosProyeccion_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiciosProyeccion
     */
    @WebEndpoint(name = "ServiciosProyeccionPort")
    public ServiciosProyeccion getServiciosProyeccionPort() {
        return super.getPort(new QName("http://ws.proyeccion.cnsv.cl/", "ServiciosProyeccionPort"), ServiciosProyeccion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciosProyeccion
     */
    @WebEndpoint(name = "ServiciosProyeccionPort")
    public ServiciosProyeccion getServiciosProyeccionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.proyeccion.cnsv.cl/", "ServiciosProyeccionPort"), ServiciosProyeccion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSPROYECCION_EXCEPTION!= null) {
            throw SERVICIOSPROYECCION_EXCEPTION;
        }
        return SERVICIOSPROYECCION_WSDL_LOCATION;
    }

}
