
package cl.cnsv.wsreporteproyeccion.cliente.proyeccion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiciosProyeccion", targetNamespace = "http://ws.proyeccion.cnsv.cl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosProyeccion {


    /**
     * 
     * @param transaccion
     * @return
     *     returns cl.cnsv.wsreporteproyeccion.cliente.proyeccion.RespuestaVidAhorro57Bis
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProyeccionVidAhorro57Bis", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorro57Bis")
    @ResponseWrapper(localName = "obtenerProyeccionVidAhorro57BisResponse", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorro57BisResponse")
    public RespuestaVidAhorro57Bis obtenerProyeccionVidAhorro57Bis(
        @WebParam(name = "transaccion", targetNamespace = "")
        TransaccionVidAhorro57Bis transaccion);

    /**
     * 
     * @param transaccion
     * @return
     *     returns cl.cnsv.wsreporteproyeccion.cliente.proyeccion.RespuestaFlexInvGold
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProyeccionFlexInvGold", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionFlexInvGold")
    @ResponseWrapper(localName = "obtenerProyeccionFlexInvGoldResponse", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionFlexInvGoldResponse")
    public RespuestaFlexInvGold obtenerProyeccionFlexInvGold(
        @WebParam(name = "transaccion", targetNamespace = "")
        TransaccionFlexInvGold transaccion);

    /**
     * 
     * @param transaccion
     * @return
     *     returns cl.cnsv.wsreporteproyeccion.cliente.proyeccion.RespuestaAhorroInternet
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProyeccionAhorroInternet", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionAhorroInternet")
    @ResponseWrapper(localName = "obtenerProyeccionAhorroInternetResponse", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionAhorroInternetResponse")
    public RespuestaAhorroInternet obtenerProyeccionAhorroInternet(
        @WebParam(name = "transaccion", targetNamespace = "")
        TransaccionAhorroInternet transaccion);

    /**
     * 
     * @param transaccion
     * @return
     *     returns cl.cnsv.wsreporteproyeccion.cliente.proyeccion.RespuestaVidAhorroFlex
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProyeccionVidAhorroFlex", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorroFlex")
    @ResponseWrapper(localName = "obtenerProyeccionVidAhorroFlexResponse", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorroFlexResponse")
    public RespuestaVidAhorroFlex obtenerProyeccionVidAhorroFlex(
        @WebParam(name = "transaccion", targetNamespace = "")
        TransaccionVidAhorroFlex transaccion);

    /**
     * 
     * @param transaccion
     * @return
     *     returns cl.cnsv.wsreporteproyeccion.cliente.proyeccion.RespuestaVidAhorro100
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProyeccionVidAhorro100", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorro100")
    @ResponseWrapper(localName = "obtenerProyeccionVidAhorro100Response", targetNamespace = "http://ws.proyeccion.cnsv.cl/", className = "cl.cnsv.wsreporteproyeccion.cliente.proyeccion.ObtenerProyeccionVidAhorro100Response")
    public RespuestaVidAhorro100 obtenerProyeccionVidAhorro100(
        @WebParam(name = "transaccion", targetNamespace = "")
        TransaccionVidAhorro100 transaccion);

}
