
package cl.cnsv.wsreporteproyeccion.cliente.cotizadorvida;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WS_CotizadorVida", targetNamespace = "http://ws.wscotizadorvida.cnsv.cl/", wsdlLocation = "http://localhost:8080/WS_CotizadorVida/WS_CotizadorVida?WSDL")
public class WSCotizadorVida_Service
    extends Service
{

    private final static URL WSCOTIZADORVIDA_WSDL_LOCATION;
    private final static WebServiceException WSCOTIZADORVIDA_EXCEPTION;
    private final static QName WSCOTIZADORVIDA_QNAME = new QName("http://ws.wscotizadorvida.cnsv.cl/", "WS_CotizadorVida");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS_CotizadorVida/WS_CotizadorVida?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSCOTIZADORVIDA_WSDL_LOCATION = url;
        WSCOTIZADORVIDA_EXCEPTION = e;
    }

    public WSCotizadorVida_Service() {
        super(__getWsdlLocation(), WSCOTIZADORVIDA_QNAME);
    }

    public WSCotizadorVida_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSCOTIZADORVIDA_QNAME, features);
    }

    public WSCotizadorVida_Service(URL wsdlLocation) {
        super(wsdlLocation, WSCOTIZADORVIDA_QNAME);
    }

    public WSCotizadorVida_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSCOTIZADORVIDA_QNAME, features);
    }

    public WSCotizadorVida_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCotizadorVida_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSCotizadorVida
     */
    @WebEndpoint(name = "WSCotizadorVidaPort")
    public WSCotizadorVida getWSCotizadorVidaPort() {
        return super.getPort(new QName("http://ws.wscotizadorvida.cnsv.cl/", "WSCotizadorVidaPort"), WSCotizadorVida.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCotizadorVida
     */
    @WebEndpoint(name = "WSCotizadorVidaPort")
    public WSCotizadorVida getWSCotizadorVidaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.wscotizadorvida.cnsv.cl/", "WSCotizadorVidaPort"), WSCotizadorVida.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSCOTIZADORVIDA_EXCEPTION!= null) {
            throw WSCOTIZADORVIDA_EXCEPTION;
        }
        return WSCOTIZADORVIDA_WSDL_LOCATION;
    }

}
